spring:
  application.name: idempotency
  data:
    redis:
      host: localhost
      port: 6380
    mongodb:
      host: localhost
      port: 27017
      database: audit_db
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    org.springframework.data.redis: INFO
    org.apache.kafka.clients: INFO
    org.springframework.kafka: INFO